"""
User model — represents an authenticated person using Amendly.

A user can belong to multiple organisations through the Membership join table.
The `plan` field tracks the billing tier at the individual level (used for
solo/personal workspace accounts). Organisation-level billing is on Organisation.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Enum, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class UserPlan(str, enum.Enum):
    """Billing plan at the user (personal workspace) level."""

    solo = "solo"
    team = "team"
    organisation = "organisation"


class User(Base):
    """
    SQLAlchemy ORM model for a platform user.

    Attributes:
        id: UUID primary key (string form, generated by Python uuid4).
        email: Unique e-mail address used for login and magic-link auth.
        name: Display name shown across the UI.
        avatar_url: Optional URL for the profile picture (from Google SSO).
        company: Optional string for the organisation the user works for.
        job_position: Optional string for the user's role / job title.
        plan: Billing tier for the user's personal workspace.
        created_at: UTC timestamp of account creation, set automatically.
        deleted_at: UTC timestamp set when the user triggers GDPR erasure (None = active).
        is_deleted: Boolean flag; True when the account has been anonymised.
        email_notifications_enabled: When False, amendment status emails are suppressed.
        is_superuser: Platform-level admin flag; grants access to /api/admin/* routes.
        notifications_last_read_at: UTC timestamp of the last time the user opened the
            in-app notification center. NULL = never opened (all entries treated as unread).
        onboarding_completed: True once the user has finished (or dismissed) the
            post-signup onboarding wizard.  Persisted server-side so the wizard is
            shown exactly once per account regardless of device.
        memberships: Back-reference to all Membership rows for this user.
    """

    __tablename__ = "users"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    company: Mapped[str | None] = mapped_column(String(255), nullable=True)
    job_position: Mapped[str | None] = mapped_column(String(255), nullable=True)
    avatar_url: Mapped[str | None] = mapped_column(String(2048), nullable=True)
    plan: Mapped[UserPlan] = mapped_column(
        Enum(UserPlan, name="user_plan"), nullable=False, default=UserPlan.solo
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    is_deleted: Mapped[bool] = mapped_column(
        Boolean(), nullable=False, default=False, server_default="false"
    )
    email_notifications_enabled: Mapped[bool] = mapped_column(
        Boolean(), nullable=False, default=True, server_default="true"
    )
    is_superuser: Mapped[bool] = mapped_column(
        Boolean(), nullable=False, default=False, server_default="false"
    )
    notifications_last_read_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    plan_expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    onboarding_completed: Mapped[bool] = mapped_column(
        Boolean(), nullable=False, default=False, server_default="false"
    )

    # Relationships
    memberships: Mapped[list["Membership"]] = relationship(  # noqa: F821
        "Membership", back_populates="user", cascade="all, delete-orphan"
    )
    amendments: Mapped[list["Amendment"]] = relationship(  # noqa: F821
        "Amendment", back_populates="author"
    )

    def __repr__(self) -> str:
        return f"<User id={self.id!r} email={self.email!r} plan={self.plan}>"
